"""fakecloud — Python SDK for the fakecloud local AWS emulator."""

from fakecloud.client import (
    ApplicationAutoScalingClient,
    BedrockAgentClient,
    BedrockAgentRuntimeClient,
    BedrockClient,
    CloudWatchClient,
    CognitoClient,
    DynamoDbClient,
    EcrClient,
    EcsClient,
    ElastiCacheClient,
    Elbv2Client,
    EventsClient,
    FakeCloud,
    FakeCloudSync,
    GlueClient,
    LambdaClient,
    LogsClient,
    OrganizationsClient,
    RdsClient,
    S3Client,
    SecretsManagerClient,
    SesClient,
    SnsClient,
    SqsClient,
)

__all__ = [
    "ApplicationAutoScalingClient",
    "BedrockAgentClient",
    "BedrockAgentRuntimeClient",
    "BedrockClient",
    "CloudWatchClient",
    "CognitoClient",
    "DynamoDbClient",
    "EcrClient",
    "EcsClient",
    "ElastiCacheClient",
    "Elbv2Client",
    "EventsClient",
    "FakeCloud",
    "FakeCloudSync",
    "GlueClient",
    "LambdaClient",
    "LogsClient",
    "OrganizationsClient",
    "RdsClient",
    "S3Client",
    "SecretsManagerClient",
    "SesClient",
    "SnsClient",
    "SqsClient",
]
