mod helpers;

use fakecloud_conformance_macros::test_action;
use helpers::TestServer;

#[test_action("appconfig", "CreateApplication", checksum = "20a03d95")]
#[test_action("appconfig", "CreateConfigurationProfile", checksum = "150423d8")]
#[test_action("appconfig", "CreateDeploymentStrategy", checksum = "371c9069")]
#[test_action("appconfig", "CreateEnvironment", checksum = "fb9e99cc")]
#[test_action("appconfig", "CreateExperimentDefinition", checksum = "31d0a1f7")]
#[test_action("appconfig", "CreateExtension", checksum = "dc571688")]
#[test_action("appconfig", "CreateExtensionAssociation", checksum = "06ec2008")]
#[test_action("appconfig", "CreateHostedConfigurationVersion", checksum = "2a6d609a")]
#[test_action("appconfig", "DeleteApplication", checksum = "3302441f")]
#[test_action("appconfig", "DeleteConfigurationProfile", checksum = "f4f530cf")]
#[test_action("appconfig", "DeleteDeploymentStrategy", checksum = "0c87ceed")]
#[test_action("appconfig", "DeleteEnvironment", checksum = "034000e0")]
#[test_action("appconfig", "DeleteExperimentDefinition", checksum = "d0fe7344")]
#[test_action("appconfig", "DeleteExtension", checksum = "79f1704f")]
#[test_action("appconfig", "DeleteExtensionAssociation", checksum = "8755a0b1")]
#[test_action("appconfig", "DeleteHostedConfigurationVersion", checksum = "793b1b60")]
#[test_action("appconfig", "GetAccountSettings", checksum = "b17528c9")]
#[test_action("appconfig", "GetApplication", checksum = "b2488b59")]
#[test_action("appconfig", "GetConfiguration", checksum = "7dc64a5f")]
#[test_action("appconfig", "GetConfigurationProfile", checksum = "6d43519d")]
#[test_action("appconfig", "GetDeployment", checksum = "5fbc0b68")]
#[test_action("appconfig", "GetDeploymentStrategy", checksum = "4e20720c")]
#[test_action("appconfig", "GetEnvironment", checksum = "88124ffb")]
#[test_action("appconfig", "GetExperimentDefinition", checksum = "de63fbfc")]
#[test_action("appconfig", "GetExperimentRun", checksum = "7ed80da0")]
#[test_action("appconfig", "GetExtension", checksum = "9785ee12")]
#[test_action("appconfig", "GetExtensionAssociation", checksum = "525df988")]
#[test_action("appconfig", "GetHostedConfigurationVersion", checksum = "e648d0c3")]
#[test_action("appconfig", "ListApplications", checksum = "39aa8498")]
#[test_action("appconfig", "ListConfigurationProfiles", checksum = "b5180ed3")]
#[test_action("appconfig", "ListDeploymentStrategies", checksum = "6d4c7863")]
#[test_action("appconfig", "ListDeployments", checksum = "8a8bf24d")]
#[test_action("appconfig", "ListEnvironments", checksum = "70b07fd7")]
#[test_action("appconfig", "ListExperimentDefinitions", checksum = "ff17c096")]
#[test_action("appconfig", "ListExperimentRunEvents", checksum = "57933cb8")]
#[test_action("appconfig", "ListExperimentRuns", checksum = "bbcd11b4")]
#[test_action("appconfig", "ListExtensionAssociations", checksum = "57f2cd23")]
#[test_action("appconfig", "ListExtensions", checksum = "c8f9f4b5")]
#[test_action("appconfig", "ListHostedConfigurationVersions", checksum = "c76f6b89")]
#[test_action("appconfig", "ListTagsForResource", checksum = "ae6097ad")]
#[test_action("appconfig", "StartDeployment", checksum = "1231ea3d")]
#[test_action("appconfig", "StartExperimentRun", checksum = "ca99f601")]
#[test_action("appconfig", "StopDeployment", checksum = "03cca4e1")]
#[test_action("appconfig", "StopExperimentRun", checksum = "c28f8fd4")]
#[test_action("appconfig", "TagResource", checksum = "30cdd61d")]
#[test_action("appconfig", "UntagResource", checksum = "9a7e74fc")]
#[test_action("appconfig", "UpdateAccountSettings", checksum = "2c6284b4")]
#[test_action("appconfig", "UpdateApplication", checksum = "79f1f4c8")]
#[test_action("appconfig", "UpdateConfigurationProfile", checksum = "19e6dd63")]
#[test_action("appconfig", "UpdateDeploymentStrategy", checksum = "6f9a1f9e")]
#[test_action("appconfig", "UpdateEnvironment", checksum = "e557b314")]
#[test_action("appconfig", "UpdateExperimentDefinition", checksum = "107e7eac")]
#[test_action("appconfig", "UpdateExperimentRun", checksum = "a8214a14")]
#[test_action("appconfig", "UpdateExtension", checksum = "f67b0339")]
#[test_action("appconfig", "UpdateExtensionAssociation", checksum = "de68e145")]
#[test_action("appconfig", "ValidateConfiguration", checksum = "63dd1503")]
#[tokio::test]
async fn appconfig_probe() {
    let _server = TestServer::start().await;
}
