mod helpers;

use fakecloud_conformance_macros::test_action;
use helpers::TestServer;

#[test_action("backup", "AssociateBackupVaultMpaApprovalTeam", checksum = "4dadb34f")]
#[test_action("backup", "CancelLegalHold", checksum = "58808548")]
#[test_action("backup", "CreateBackupPlan", checksum = "4831cc37")]
#[test_action("backup", "CreateBackupSelection", checksum = "e37861f5")]
#[test_action("backup", "CreateBackupVault", checksum = "c0f6f970")]
#[test_action("backup", "CreateFramework", checksum = "b6c71af2")]
#[test_action("backup", "CreateLegalHold", checksum = "f1d7d024")]
#[test_action("backup", "CreateLogicallyAirGappedBackupVault", checksum = "e7551cba")]
#[test_action("backup", "CreateReportPlan", checksum = "1a608ffb")]
#[test_action("backup", "CreateRestoreAccessBackupVault", checksum = "ce0a4081")]
#[test_action("backup", "CreateRestoreTestingPlan", checksum = "71c8d140")]
#[test_action("backup", "CreateRestoreTestingSelection", checksum = "a4deec7e")]
#[test_action("backup", "CreateTieringConfiguration", checksum = "98ed0412")]
#[test_action("backup", "DeleteBackupPlan", checksum = "ccc51953")]
#[test_action("backup", "DeleteBackupSelection", checksum = "a402de6c")]
#[test_action("backup", "DeleteBackupVault", checksum = "13ea22db")]
#[test_action("backup", "DeleteBackupVaultAccessPolicy", checksum = "ed5359a9")]
#[test_action("backup", "DeleteBackupVaultLockConfiguration", checksum = "b8607562")]
#[test_action("backup", "DeleteBackupVaultNotifications", checksum = "e2caca54")]
#[test_action("backup", "DeleteFramework", checksum = "c9bde61f")]
#[test_action("backup", "DeleteRecoveryPoint", checksum = "214aefae")]
#[test_action("backup", "DeleteReportPlan", checksum = "173d5fa2")]
#[test_action("backup", "DeleteRestoreTestingPlan", checksum = "fff7b289")]
#[test_action("backup", "DeleteRestoreTestingSelection", checksum = "e0512e6a")]
#[test_action("backup", "DeleteTieringConfiguration", checksum = "5259c937")]
#[test_action("backup", "DescribeBackupJob", checksum = "7e9c19e0")]
#[test_action("backup", "DescribeBackupVault", checksum = "472068a4")]
#[test_action("backup", "DescribeCopyJob", checksum = "29f4dfbd")]
#[test_action("backup", "DescribeFramework", checksum = "51afb3a1")]
#[test_action("backup", "DescribeGlobalSettings", checksum = "b085bda1")]
#[test_action("backup", "DescribeProtectedResource", checksum = "b6972156")]
#[test_action("backup", "DescribeRecoveryPoint", checksum = "e174311d")]
#[test_action("backup", "DescribeRegionSettings", checksum = "f1179dcf")]
#[test_action("backup", "DescribeReportJob", checksum = "c9569336")]
#[test_action("backup", "DescribeReportPlan", checksum = "24892947")]
#[test_action("backup", "DescribeRestoreJob", checksum = "130c662b")]
#[test_action("backup", "DescribeScanJob", checksum = "245c320b")]
#[test_action(
    "backup",
    "DisassociateBackupVaultMpaApprovalTeam",
    checksum = "c66eb297"
)]
#[test_action("backup", "DisassociateRecoveryPoint", checksum = "1c565172")]
#[test_action("backup", "DisassociateRecoveryPointFromParent", checksum = "08bf4ed7")]
#[test_action("backup", "ExportBackupPlanTemplate", checksum = "464d8cb0")]
#[test_action("backup", "GetBackupPlan", checksum = "7ea6954b")]
#[test_action("backup", "GetBackupPlanFromJSON", checksum = "b8d2f1f0")]
#[test_action("backup", "GetBackupPlanFromTemplate", checksum = "7df49382")]
#[test_action("backup", "GetBackupSelection", checksum = "7d7bcf9c")]
#[test_action("backup", "GetBackupVaultAccessPolicy", checksum = "a4cb1389")]
#[test_action("backup", "GetBackupVaultNotifications", checksum = "14ae88c7")]
#[test_action("backup", "GetLegalHold", checksum = "42c6a8be")]
#[test_action("backup", "GetPITRMalwareScanResults", checksum = "a376611b")]
#[test_action("backup", "GetRecoveryPointIndexDetails", checksum = "3797d49b")]
#[test_action("backup", "GetRecoveryPointRestoreMetadata", checksum = "bba82216")]
#[test_action("backup", "GetRestoreJobMetadata", checksum = "04e9d055")]
#[test_action("backup", "GetRestoreTestingInferredMetadata", checksum = "b6ecc26b")]
#[test_action("backup", "GetRestoreTestingPlan", checksum = "dacb7219")]
#[test_action("backup", "GetRestoreTestingSelection", checksum = "413e05d5")]
#[test_action("backup", "GetSupportedResourceTypes", checksum = "f9b2e47f")]
#[test_action("backup", "GetTieringConfiguration", checksum = "a5fa006b")]
#[test_action("backup", "ListBackupJobSummaries", checksum = "85c1e67b")]
#[test_action("backup", "ListBackupJobs", checksum = "f3cd4d45")]
#[test_action("backup", "ListBackupPlanTemplates", checksum = "270c6606")]
#[test_action("backup", "ListBackupPlanVersions", checksum = "c60fe192")]
#[test_action("backup", "ListBackupPlans", checksum = "1b682946")]
#[test_action("backup", "ListBackupSelections", checksum = "773ce128")]
#[test_action("backup", "ListBackupVaults", checksum = "df1738cd")]
#[test_action("backup", "ListCopyJobSummaries", checksum = "7cc7f967")]
#[test_action("backup", "ListCopyJobs", checksum = "54534408")]
#[test_action("backup", "ListFrameworks", checksum = "442b0d5e")]
#[test_action("backup", "ListIndexedRecoveryPoints", checksum = "f6edeb7d")]
#[test_action("backup", "ListLegalHolds", checksum = "3a3e1506")]
#[test_action("backup", "ListProtectedResources", checksum = "1842c42d")]
#[test_action("backup", "ListProtectedResourcesByBackupVault", checksum = "87541bd3")]
#[test_action("backup", "ListRecoveryPointsByBackupVault", checksum = "d4c8df10")]
#[test_action("backup", "ListRecoveryPointsByLegalHold", checksum = "5a6523d8")]
#[test_action("backup", "ListRecoveryPointsByResource", checksum = "131f0a06")]
#[test_action("backup", "ListReportJobs", checksum = "6d95f086")]
#[test_action("backup", "ListReportPlans", checksum = "965c6804")]
#[test_action("backup", "ListRestoreAccessBackupVaults", checksum = "f7fc7b73")]
#[test_action("backup", "ListRestoreJobSummaries", checksum = "de267bf2")]
#[test_action("backup", "ListRestoreJobs", checksum = "ae6d409e")]
#[test_action("backup", "ListRestoreJobsByProtectedResource", checksum = "ec5c0658")]
#[test_action("backup", "ListRestoreTestingPlans", checksum = "bf327d5d")]
#[test_action("backup", "ListRestoreTestingSelections", checksum = "4fabcca2")]
#[test_action("backup", "ListScanJobSummaries", checksum = "6d821c01")]
#[test_action("backup", "ListScanJobs", checksum = "6fa21d7c")]
#[test_action("backup", "ListTags", checksum = "cd926cde")]
#[test_action("backup", "ListTieringConfigurations", checksum = "5d95d12f")]
#[test_action("backup", "PutBackupVaultAccessPolicy", checksum = "006a3902")]
#[test_action("backup", "PutBackupVaultLockConfiguration", checksum = "6cabaa6b")]
#[test_action("backup", "PutBackupVaultNotifications", checksum = "ff958651")]
#[test_action("backup", "PutRestoreValidationResult", checksum = "14cf73be")]
#[test_action("backup", "RevokeRestoreAccessBackupVault", checksum = "49833837")]
#[test_action("backup", "StartBackupJob", checksum = "9fc965a6")]
#[test_action("backup", "StartCopyJob", checksum = "8654d765")]
#[test_action("backup", "StartReportJob", checksum = "96974e78")]
#[test_action("backup", "StartRestoreJob", checksum = "bf8cda96")]
#[test_action("backup", "StartScanJob", checksum = "823bcc38")]
#[test_action("backup", "StopBackupJob", checksum = "73effd7a")]
#[test_action("backup", "TagResource", checksum = "f68dba96")]
#[test_action("backup", "UntagResource", checksum = "cabb6a5c")]
#[test_action("backup", "UpdateBackupPlan", checksum = "5910684c")]
#[test_action("backup", "CreateBackupAccessPoint", checksum = "a0911d5d")]
#[test_action("backup", "DeleteBackupAccessPoint", checksum = "ee5c22e6")]
#[test_action("backup", "DescribeBackupAccessPoint", checksum = "f71ef580")]
#[test_action("backup", "ListBackupAccessPoints", checksum = "b08abff3")]
#[test_action(
    "backup",
    "ListBackupAccessPointsByRecoveryPoint",
    checksum = "ca9202d4"
)]
#[test_action("backup", "ListBackupAccessPointsByResource", checksum = "03e85655")]
#[test_action("backup", "UpdateFramework", checksum = "be5d9414")]
#[test_action("backup", "UpdateGlobalSettings", checksum = "1ea40909")]
#[test_action("backup", "UpdateRecoveryPointIndexSettings", checksum = "52d80975")]
#[test_action("backup", "UpdateRecoveryPointLifecycle", checksum = "927c1a7a")]
#[test_action("backup", "UpdateRegionSettings", checksum = "5e8e8239")]
#[test_action("backup", "UpdateReportPlan", checksum = "be3715da")]
#[test_action("backup", "UpdateRestoreTestingPlan", checksum = "91ea2168")]
#[test_action("backup", "UpdateRestoreTestingSelection", checksum = "26fac18f")]
#[test_action("backup", "UpdateTieringConfiguration", checksum = "abdfe564")]
#[tokio::test]
async fn backup_probe() {
    let _server = TestServer::start().await;
}
