mod helpers;

use fakecloud_conformance_macros::test_action;
use helpers::TestServer;

#[test_action("codebuild", "BatchDeleteBuilds", checksum = "e68aaada")]
#[test_action("codebuild", "BatchGetBuildBatches", checksum = "1e9700c1")]
#[test_action("codebuild", "BatchGetBuilds", checksum = "9d8c50e5")]
#[test_action("codebuild", "BatchGetCommandExecutions", checksum = "df399050")]
#[test_action("codebuild", "BatchGetFleets", checksum = "3e157905")]
#[test_action("codebuild", "BatchGetProjects", checksum = "1f2e70a7")]
#[test_action("codebuild", "BatchGetReportGroups", checksum = "291df7fb")]
#[test_action("codebuild", "BatchGetReports", checksum = "4748fbe5")]
#[test_action("codebuild", "BatchGetSandboxes", checksum = "766f5282")]
#[test_action("codebuild", "CreateFleet", checksum = "09948277")]
#[test_action("codebuild", "CreateProject", checksum = "08e06379")]
#[test_action("codebuild", "CreateReportGroup", checksum = "f25204b4")]
#[test_action("codebuild", "CreateWebhook", checksum = "8e853c71")]
#[test_action("codebuild", "DeleteBuildBatch", checksum = "21551c33")]
#[test_action("codebuild", "DeleteFleet", checksum = "92f55663")]
#[test_action("codebuild", "DeleteProject", checksum = "098974e9")]
#[test_action("codebuild", "DeleteReport", checksum = "2db1eaee")]
#[test_action("codebuild", "DeleteReportGroup", checksum = "f065f308")]
#[test_action("codebuild", "DeleteResourcePolicy", checksum = "85077ac1")]
#[test_action("codebuild", "DeleteSourceCredentials", checksum = "838bcd13")]
#[test_action("codebuild", "DeleteWebhook", checksum = "59332719")]
#[test_action("codebuild", "DescribeCodeCoverages", checksum = "1905e1ad")]
#[test_action("codebuild", "DescribeTestCases", checksum = "1f8f7c85")]
#[test_action("codebuild", "GetReportGroupTrend", checksum = "6989abb3")]
#[test_action("codebuild", "GetResourcePolicy", checksum = "31181ba1")]
#[test_action("codebuild", "ImportSourceCredentials", checksum = "bfaf1a9f")]
#[test_action("codebuild", "InvalidateProjectCache", checksum = "45e5ebd8")]
#[test_action("codebuild", "ListBuildBatches", checksum = "765b2186")]
#[test_action("codebuild", "ListBuildBatchesForProject", checksum = "282b1aa4")]
#[test_action("codebuild", "ListBuilds", checksum = "74ac1c6d")]
#[test_action("codebuild", "ListBuildsForProject", checksum = "9d43d184")]
#[test_action("codebuild", "ListCommandExecutionsForSandbox", checksum = "46d09c20")]
#[test_action("codebuild", "ListCuratedEnvironmentImages", checksum = "bae8633d")]
#[test_action("codebuild", "ListFleets", checksum = "5d353c62")]
#[test_action("codebuild", "ListProjects", checksum = "24df4cc1")]
#[test_action("codebuild", "ListReportGroups", checksum = "54cfa60c")]
#[test_action("codebuild", "ListReports", checksum = "1e70ca12")]
#[test_action("codebuild", "ListReportsForReportGroup", checksum = "fd3b5517")]
#[test_action("codebuild", "ListSandboxes", checksum = "fd2d1228")]
#[test_action("codebuild", "ListSandboxesForProject", checksum = "386108ee")]
#[test_action("codebuild", "ListSharedProjects", checksum = "2bbbb725")]
#[test_action("codebuild", "ListSharedReportGroups", checksum = "5bdfa267")]
#[test_action("codebuild", "ListSourceCredentials", checksum = "5486c091")]
#[test_action("codebuild", "PutResourcePolicy", checksum = "8ee83d97")]
#[test_action("codebuild", "RetryBuild", checksum = "9a1f4080")]
#[test_action("codebuild", "RetryBuildBatch", checksum = "51ebf701")]
#[test_action("codebuild", "StartBuild", checksum = "80005024")]
#[test_action("codebuild", "StartBuildBatch", checksum = "9560aa29")]
#[test_action("codebuild", "StartCommandExecution", checksum = "83e8ef86")]
#[test_action("codebuild", "StartSandbox", checksum = "62210f2a")]
#[test_action("codebuild", "StartSandboxConnection", checksum = "a18d08bf")]
#[test_action("codebuild", "StopBuild", checksum = "36d361ed")]
#[test_action("codebuild", "StopBuildBatch", checksum = "26b3d48c")]
#[test_action("codebuild", "StopSandbox", checksum = "fb0c91a5")]
#[test_action("codebuild", "UpdateFleet", checksum = "a1f5840a")]
#[test_action("codebuild", "UpdateProject", checksum = "178b07f8")]
#[test_action("codebuild", "UpdateProjectVisibility", checksum = "2f414451")]
#[test_action("codebuild", "UpdateReportGroup", checksum = "039c3475")]
#[test_action("codebuild", "UpdateWebhook", checksum = "6f59496c")]
#[tokio::test]
async fn codebuild_conformance() {
    let _server = TestServer::start().await;
}
