mod helpers;

use fakecloud_conformance_macros::test_action;
use helpers::TestServer;

#[test_action("docdb", "AddSourceIdentifierToSubscription", checksum = "34b88d96")]
#[test_action("docdb", "AddTagsToResource", checksum = "ae5a9cdf")]
#[test_action("docdb", "ApplyPendingMaintenanceAction", checksum = "e66af7e3")]
#[test_action("docdb", "CopyDBClusterParameterGroup", checksum = "7cd1d8ac")]
#[test_action("docdb", "CopyDBClusterSnapshot", checksum = "b8b04fa2")]
#[test_action("docdb", "CreateDBCluster", checksum = "de6f735e")]
#[test_action("docdb", "CreateDBClusterParameterGroup", checksum = "5e9963a6")]
#[test_action("docdb", "CreateDBClusterSnapshot", checksum = "e576d111")]
#[test_action("docdb", "CreateDBInstance", checksum = "b0124e03")]
#[test_action("docdb", "CreateDBSubnetGroup", checksum = "29f0d10f")]
#[test_action("docdb", "CreateEventSubscription", checksum = "678f6408")]
#[test_action("docdb", "CreateGlobalCluster", checksum = "53e31437")]
#[test_action("docdb", "DeleteDBCluster", checksum = "3c7f86a3")]
#[test_action("docdb", "DeleteDBClusterParameterGroup", checksum = "87107a96")]
#[test_action("docdb", "DeleteDBClusterSnapshot", checksum = "9b21b70e")]
#[test_action("docdb", "DeleteDBInstance", checksum = "b2abc97a")]
#[test_action("docdb", "DeleteDBSubnetGroup", checksum = "5b471377")]
#[test_action("docdb", "DeleteEventSubscription", checksum = "b58ce3ff")]
#[test_action("docdb", "DeleteGlobalCluster", checksum = "16454696")]
#[test_action("docdb", "DescribeCertificates", checksum = "9c978533")]
#[test_action("docdb", "DescribeDBClusterParameterGroups", checksum = "44e5b54b")]
#[test_action("docdb", "DescribeDBClusterParameters", checksum = "c4301251")]
#[test_action("docdb", "DescribeDBClusterSnapshotAttributes", checksum = "45323967")]
#[test_action("docdb", "DescribeDBClusterSnapshots", checksum = "ccb623ee")]
#[test_action("docdb", "DescribeDBClusters", checksum = "9e30429c")]
#[test_action("docdb", "DescribeDBEngineVersions", checksum = "bbccf21e")]
#[test_action("docdb", "DescribeDBInstances", checksum = "c1f39bae")]
#[test_action("docdb", "DescribeDBSubnetGroups", checksum = "8ce472cc")]
#[test_action("docdb", "DescribeEngineDefaultClusterParameters", checksum = "2fbe3959")]
#[test_action("docdb", "DescribeEventCategories", checksum = "a53a3236")]
#[test_action("docdb", "DescribeEventSubscriptions", checksum = "85ea84d2")]
#[test_action("docdb", "DescribeEvents", checksum = "daf8d02e")]
#[test_action("docdb", "DescribeGlobalClusters", checksum = "b5018327")]
#[test_action("docdb", "DescribeOrderableDBInstanceOptions", checksum = "a3f52509")]
#[test_action("docdb", "DescribePendingMaintenanceActions", checksum = "dfc566cc")]
#[test_action("docdb", "FailoverDBCluster", checksum = "47d93cfe")]
#[test_action("docdb", "FailoverGlobalCluster", checksum = "263fb7b2")]
#[test_action("docdb", "ListTagsForResource", checksum = "cefe5ebd")]
#[test_action("docdb", "ModifyDBCluster", checksum = "322a5add")]
#[test_action("docdb", "ModifyDBClusterParameterGroup", checksum = "72c30f87")]
#[test_action("docdb", "ModifyDBClusterSnapshotAttribute", checksum = "5e922a8b")]
#[test_action("docdb", "ModifyDBInstance", checksum = "e4c180bf")]
#[test_action("docdb", "ModifyDBSubnetGroup", checksum = "bab081bc")]
#[test_action("docdb", "ModifyEventSubscription", checksum = "97894d7a")]
#[test_action("docdb", "ModifyGlobalCluster", checksum = "dce9be8f")]
#[test_action("docdb", "RebootDBInstance", checksum = "dc6a7a1d")]
#[test_action("docdb", "RemoveFromGlobalCluster", checksum = "78f873cd")]
#[test_action("docdb", "RemoveSourceIdentifierFromSubscription", checksum = "1480f1e3")]
#[test_action("docdb", "RemoveTagsFromResource", checksum = "229ee44d")]
#[test_action("docdb", "ResetDBClusterParameterGroup", checksum = "5f0e38d9")]
#[test_action("docdb", "RestoreDBClusterFromSnapshot", checksum = "56d3c868")]
#[test_action("docdb", "RestoreDBClusterToPointInTime", checksum = "bb29ee9c")]
#[test_action("docdb", "StartDBCluster", checksum = "7cf84756")]
#[test_action("docdb", "StopDBCluster", checksum = "82ed2fff")]
#[test_action("docdb", "SwitchoverGlobalCluster", checksum = "0854cfcc")]
#[tokio::test]
async fn docdb_probe() {
    let _server = TestServer::start().await;
}
