mod helpers;

use fakecloud_conformance_macros::test_action;
use helpers::TestServer;

#[test_action("eks", "CreateCluster", checksum = "89446e5c")]
#[test_action("eks", "DescribeCluster", checksum = "b6b3efc6")]
#[test_action("eks", "ListClusters", checksum = "464ec628")]
#[test_action("eks", "DeleteCluster", checksum = "9ebb66d0")]
#[test_action("eks", "UpdateClusterConfig", checksum = "8dce51aa")]
#[test_action("eks", "UpdateClusterVersion", checksum = "749042fc")]
#[test_action("eks", "DescribeUpdate", checksum = "1f003008")]
#[test_action("eks", "ListUpdates", checksum = "7e756829")]
#[test_action("eks", "TagResource", checksum = "e443c80e")]
#[test_action("eks", "UntagResource", checksum = "94806184")]
#[test_action("eks", "ListTagsForResource", checksum = "7abc6464")]
#[test_action("eks", "CreateNodegroup", checksum = "5d67a876")]
#[test_action("eks", "DescribeNodegroup", checksum = "9ab7ed2c")]
#[test_action("eks", "ListNodegroups", checksum = "773ab1a2")]
#[test_action("eks", "DeleteNodegroup", checksum = "f27dc5b7")]
#[test_action("eks", "UpdateNodegroupConfig", checksum = "925299f2")]
#[test_action("eks", "UpdateNodegroupVersion", checksum = "bdcd4d52")]
#[test_action("eks", "CreateFargateProfile", checksum = "1ca54862")]
#[test_action("eks", "DescribeFargateProfile", checksum = "0a697095")]
#[test_action("eks", "ListFargateProfiles", checksum = "3416e569")]
#[test_action("eks", "DeleteFargateProfile", checksum = "2163f559")]
#[test_action("eks", "CreateAddon", checksum = "304277ce")]
#[test_action("eks", "DescribeAddon", checksum = "6d44165d")]
#[test_action("eks", "ListAddons", checksum = "9d82853d")]
#[test_action("eks", "DeleteAddon", checksum = "f5e41a86")]
#[test_action("eks", "UpdateAddon", checksum = "eee6e57e")]
#[test_action("eks", "DescribeAddonVersions", checksum = "bc128dba")]
#[test_action("eks", "DescribeAddonConfiguration", checksum = "29c08d92")]
#[test_action("eks", "CreateAccessEntry", checksum = "780d0f0b")]
#[test_action("eks", "DescribeAccessEntry", checksum = "b2efed3f")]
#[test_action("eks", "ListAccessEntries", checksum = "9fe261b6")]
#[test_action("eks", "DeleteAccessEntry", checksum = "ee16b5a4")]
#[test_action("eks", "UpdateAccessEntry", checksum = "007ebd20")]
#[test_action("eks", "AssociateAccessPolicy", checksum = "ad63ee66")]
#[test_action("eks", "DisassociateAccessPolicy", checksum = "aed9926c")]
#[test_action("eks", "ListAssociatedAccessPolicies", checksum = "a6a37560")]
#[test_action("eks", "ListAccessPolicies", checksum = "fd7435db")]
#[test_action("eks", "AssociateIdentityProviderConfig", checksum = "28337c96")]
#[test_action("eks", "DisassociateIdentityProviderConfig", checksum = "8038f710")]
#[test_action("eks", "DescribeIdentityProviderConfig", checksum = "b03d8b74")]
#[test_action("eks", "ListIdentityProviderConfigs", checksum = "f69f1b4a")]
#[test_action("eks", "CreatePodIdentityAssociation", checksum = "a6248f17")]
#[test_action("eks", "DeletePodIdentityAssociation", checksum = "17321542")]
#[test_action("eks", "DescribePodIdentityAssociation", checksum = "fd7fe00b")]
#[test_action("eks", "ListPodIdentityAssociations", checksum = "6c32e5fa")]
#[test_action("eks", "UpdatePodIdentityAssociation", checksum = "7376e4fa")]
#[test_action("eks", "DescribeInsight", checksum = "3b7856fc")]
#[test_action("eks", "ListInsights", checksum = "0ed22aa2")]
#[test_action("eks", "DescribeInsightsRefresh", checksum = "396cecc0")]
#[test_action("eks", "StartInsightsRefresh", checksum = "2982bc3d")]
#[test_action("eks", "AssociateEncryptionConfig", checksum = "f5f06215")]
#[test_action("eks", "CancelUpdate", checksum = "e660aa52")]
#[test_action("eks", "DeregisterCluster", checksum = "3fc26268")]
#[test_action("eks", "RegisterCluster", checksum = "1ce1d14e")]
#[test_action("eks", "DescribeClusterVersions", checksum = "5588aca9")]
#[test_action("eks", "CreateCapability", checksum = "4581d702")]
#[test_action("eks", "DeleteCapability", checksum = "f34895dc")]
#[test_action("eks", "DescribeCapability", checksum = "1aca991f")]
#[test_action("eks", "ListCapabilities", checksum = "fc80dae5")]
#[test_action("eks", "UpdateCapability", checksum = "50f68794")]
#[test_action("eks", "CreateEksAnywhereSubscription", checksum = "8c078578")]
#[test_action("eks", "DeleteEksAnywhereSubscription", checksum = "fc2ba1c2")]
#[test_action("eks", "DescribeEksAnywhereSubscription", checksum = "c8a0063b")]
#[test_action("eks", "ListEksAnywhereSubscriptions", checksum = "e204ce93")]
#[test_action("eks", "UpdateEksAnywhereSubscription", checksum = "7410f68d")]
#[tokio::test]
async fn eks_probe() {
    let _server = TestServer::start().await;
}
