mod helpers;

use fakecloud_conformance_macros::test_action;
use helpers::TestServer;

#[test_action("emr", "AddInstanceFleet", checksum = "d2b7d7c0")]
#[test_action("emr", "AddInstanceGroups", checksum = "955cbdda")]
#[test_action("emr", "AddJobFlowSteps", checksum = "623a8483")]
#[test_action("emr", "AddTags", checksum = "a324f02d")]
#[test_action("emr", "CancelSteps", checksum = "32d7dfd7")]
#[test_action("emr", "CreatePersistentAppUI", checksum = "9aaba29d")]
#[test_action("emr", "CreateSecurityConfiguration", checksum = "3f9d4ddf")]
#[test_action("emr", "CreateStudio", checksum = "5979103a")]
#[test_action("emr", "CreateStudioSessionMapping", checksum = "9e5feee0")]
#[test_action("emr", "DeleteSecurityConfiguration", checksum = "6fc131f5")]
#[test_action("emr", "DeleteStudio", checksum = "e28b000e")]
#[test_action("emr", "DeleteStudioSessionMapping", checksum = "93cebd50")]
#[test_action("emr", "DescribeCluster", checksum = "5d388175")]
#[test_action("emr", "DescribeJobFlows", checksum = "7347b62b")]
#[test_action("emr", "DescribeNotebookExecution", checksum = "707a8392")]
#[test_action("emr", "DescribePersistentAppUI", checksum = "92a6c7f2")]
#[test_action("emr", "DescribeReleaseLabel", checksum = "af9da7a1")]
#[test_action("emr", "DescribeSecurityConfiguration", checksum = "dd0a4b77")]
#[test_action("emr", "DescribeStep", checksum = "1ae04d35")]
#[test_action("emr", "DescribeStudio", checksum = "52a174ce")]
#[test_action("emr", "GetAutoTerminationPolicy", checksum = "bb719298")]
#[test_action("emr", "GetBlockPublicAccessConfiguration", checksum = "88b446ec")]
#[test_action("emr", "GetClusterSessionCredentials", checksum = "54bb7cb1")]
#[test_action("emr", "GetManagedScalingPolicy", checksum = "6aeb86d5")]
#[test_action("emr", "GetOnClusterAppUIPresignedURL", checksum = "6d59beb6")]
#[test_action("emr", "GetPersistentAppUIPresignedURL", checksum = "46df69f0")]
#[test_action("emr", "GetSession", checksum = "c4683e0e")]
#[test_action("emr", "GetSessionEndpoint", checksum = "b3c8b9dc")]
#[test_action("emr", "GetStudioSessionMapping", checksum = "53bc6390")]
#[test_action("emr", "ListBootstrapActions", checksum = "60b102a7")]
#[test_action("emr", "ListClusters", checksum = "c7747256")]
#[test_action("emr", "ListInstanceFleets", checksum = "47d4ba00")]
#[test_action("emr", "ListInstanceGroups", checksum = "d6fa778e")]
#[test_action("emr", "ListInstances", checksum = "0ad4f818")]
#[test_action("emr", "ListNotebookExecutions", checksum = "b10f7cd0")]
#[test_action("emr", "ListReleaseLabels", checksum = "e4d60dcd")]
#[test_action("emr", "ListSecurityConfigurations", checksum = "b1677ba2")]
#[test_action("emr", "ListSessions", checksum = "a109ff4c")]
#[test_action("emr", "ListSteps", checksum = "bb2ecb86")]
#[test_action("emr", "ListStudioSessionMappings", checksum = "412dc0ab")]
#[test_action("emr", "ListStudios", checksum = "535e951a")]
#[test_action("emr", "ListSupportedInstanceTypes", checksum = "5d284a42")]
#[test_action("emr", "ModifyCluster", checksum = "42b1d6bf")]
#[test_action("emr", "ModifyInstanceFleet", checksum = "612e35a7")]
#[test_action("emr", "ModifyInstanceGroups", checksum = "a1e44ca3")]
#[test_action("emr", "PutAutoScalingPolicy", checksum = "052aee2c")]
#[test_action("emr", "PutAutoTerminationPolicy", checksum = "663771ec")]
#[test_action("emr", "PutBlockPublicAccessConfiguration", checksum = "d9de9715")]
#[test_action("emr", "PutManagedScalingPolicy", checksum = "16b6c362")]
#[test_action("emr", "RemoveAutoScalingPolicy", checksum = "60aab9d2")]
#[test_action("emr", "RemoveAutoTerminationPolicy", checksum = "45b7e555")]
#[test_action("emr", "RemoveManagedScalingPolicy", checksum = "8b1864c1")]
#[test_action("emr", "RemoveTags", checksum = "8e3b68ce")]
#[test_action("emr", "RunJobFlow", checksum = "b09a0407")]
#[test_action("emr", "SetKeepJobFlowAliveWhenNoSteps", checksum = "db8292cf")]
#[test_action("emr", "SetTerminationProtection", checksum = "63b28c9c")]
#[test_action("emr", "SetUnhealthyNodeReplacement", checksum = "6334daa7")]
#[test_action("emr", "SetVisibleToAllUsers", checksum = "546da870")]
#[test_action("emr", "StartNotebookExecution", checksum = "b8467ce7")]
#[test_action("emr", "StartSession", checksum = "180ec850")]
#[test_action("emr", "StopNotebookExecution", checksum = "fc8163c0")]
#[test_action("emr", "TerminateJobFlows", checksum = "7089452c")]
#[test_action("emr", "TerminateSession", checksum = "dad11f52")]
#[test_action("emr", "UpdateStudio", checksum = "233aa261")]
#[test_action("emr", "UpdateStudioSessionMapping", checksum = "556498c8")]
#[tokio::test]
async fn emr_probe() {
    let _server = TestServer::start().await;
}
