mod helpers;

use fakecloud_conformance_macros::test_action;
use helpers::TestServer;

#[test_action("kafka", "BatchAssociateScramSecret", checksum = "eca7f60f")]
#[test_action("kafka", "BatchDisassociateScramSecret", checksum = "0a717073")]
#[test_action("kafka", "CreateCluster", checksum = "d1c58409")]
#[test_action("kafka", "CreateClusterV2", checksum = "921956a1")]
#[test_action("kafka", "CreateConfiguration", checksum = "2d611cc6")]
#[test_action("kafka", "CreateReplicator", checksum = "3058181d")]
#[test_action("kafka", "CreateTopic", checksum = "292650ae")]
#[test_action("kafka", "CreateVpcConnection", checksum = "9076d349")]
#[test_action("kafka", "DeleteCluster", checksum = "2b0ff8d6")]
#[test_action("kafka", "DeleteClusterPolicy", checksum = "a060a0ca")]
#[test_action("kafka", "DeleteConfiguration", checksum = "4cc3adb2")]
#[test_action("kafka", "DeleteReplicator", checksum = "504b2c9a")]
#[test_action("kafka", "DeleteTopic", checksum = "5909dcbc")]
#[test_action("kafka", "DeleteVpcConnection", checksum = "87067d0e")]
#[test_action("kafka", "DescribeCluster", checksum = "ad7662e7")]
#[test_action("kafka", "DescribeClusterOperation", checksum = "6acccea2")]
#[test_action("kafka", "DescribeClusterOperationV2", checksum = "93eded8a")]
#[test_action("kafka", "DescribeClusterV2", checksum = "32d402a5")]
#[test_action("kafka", "DescribeConfiguration", checksum = "a7a65191")]
#[test_action("kafka", "DescribeConfigurationRevision", checksum = "7216bcf5")]
#[test_action("kafka", "DescribeReplicator", checksum = "29dd61c2")]
#[test_action("kafka", "DescribeTopic", checksum = "6fcad32c")]
#[test_action("kafka", "DescribeTopicPartitions", checksum = "0bdaf5ac")]
#[test_action("kafka", "DescribeVpcConnection", checksum = "f546e177")]
#[test_action("kafka", "GetBootstrapBrokers", checksum = "f3b96ac3")]
#[test_action("kafka", "GetClusterPolicy", checksum = "a3a7c212")]
#[test_action("kafka", "GetCompatibleKafkaVersions", checksum = "6524c074")]
#[test_action("kafka", "ListClientVpcConnections", checksum = "500af701")]
#[test_action("kafka", "ListClusterOperations", checksum = "dde95208")]
#[test_action("kafka", "ListClusterOperationsV2", checksum = "b1b59c1a")]
#[test_action("kafka", "ListClusters", checksum = "db63424e")]
#[test_action("kafka", "ListClustersV2", checksum = "948184a3")]
#[test_action("kafka", "ListConfigurationRevisions", checksum = "f868abaf")]
#[test_action("kafka", "ListConfigurations", checksum = "4b8cb2df")]
#[test_action("kafka", "ListKafkaVersions", checksum = "9b556949")]
#[test_action("kafka", "ListNodes", checksum = "ab37a892")]
#[test_action("kafka", "ListReplicators", checksum = "8fff88ad")]
#[test_action("kafka", "ListScramSecrets", checksum = "655045e8")]
#[test_action("kafka", "ListTagsForResource", checksum = "a9a04746")]
#[test_action("kafka", "ListTopics", checksum = "6d5e8db4")]
#[test_action("kafka", "ListVpcConnections", checksum = "256e8906")]
#[test_action("kafka", "PutClusterPolicy", checksum = "376d648d")]
#[test_action("kafka", "RebootBroker", checksum = "e86e21c7")]
#[test_action("kafka", "RejectClientVpcConnection", checksum = "261afbe4")]
#[test_action("kafka", "TagResource", checksum = "c39546ad")]
#[test_action("kafka", "UntagResource", checksum = "90bab122")]
#[test_action("kafka", "UpdateBrokerCount", checksum = "fb7eee37")]
#[test_action("kafka", "UpdateBrokerStorage", checksum = "e1cdae4f")]
#[test_action("kafka", "UpdateBrokerType", checksum = "f4970fea")]
#[test_action("kafka", "UpdateClusterConfiguration", checksum = "ca2a7a42")]
#[test_action("kafka", "UpdateClusterKafkaVersion", checksum = "45c184ab")]
#[test_action("kafka", "UpdateConfiguration", checksum = "ceda0807")]
#[test_action("kafka", "UpdateConnectivity", checksum = "4c6361b4")]
#[test_action("kafka", "UpdateMonitoring", checksum = "590bb038")]
#[test_action("kafka", "UpdateRebalancing", checksum = "513fce61")]
#[test_action("kafka", "UpdateReplicationInfo", checksum = "28e45f73")]
#[test_action("kafka", "UpdateSecurity", checksum = "9714d461")]
#[test_action("kafka", "UpdateStorage", checksum = "5d0cc3ed")]
#[test_action("kafka", "UpdateTopic", checksum = "1c0c9a33")]
#[tokio::test]
async fn kafka_conformance() {
    let _server = TestServer::start().await;
}
