mod helpers;

use fakecloud_conformance_macros::test_action;
use helpers::TestServer;

#[test_action("neptune", "AddRoleToDBCluster", checksum = "9ebf0afb")]
#[test_action("neptune", "AddSourceIdentifierToSubscription", checksum = "91977c6a")]
#[test_action("neptune", "AddTagsToResource", checksum = "09bc6c8b")]
#[test_action("neptune", "ApplyPendingMaintenanceAction", checksum = "71427bae")]
#[test_action("neptune", "CopyDBClusterParameterGroup", checksum = "9423a12c")]
#[test_action("neptune", "CopyDBClusterSnapshot", checksum = "7a0b24b8")]
#[test_action("neptune", "CopyDBParameterGroup", checksum = "5603bd7e")]
#[test_action("neptune", "CreateDBCluster", checksum = "56b7b4f1")]
#[test_action("neptune", "CreateDBClusterEndpoint", checksum = "93f3e73b")]
#[test_action("neptune", "CreateDBClusterParameterGroup", checksum = "f802cbd5")]
#[test_action("neptune", "CreateDBClusterSnapshot", checksum = "6fcb27a3")]
#[test_action("neptune", "CreateDBInstance", checksum = "45038b3b")]
#[test_action("neptune", "CreateDBParameterGroup", checksum = "db7a5bed")]
#[test_action("neptune", "CreateDBSubnetGroup", checksum = "b5eb25b4")]
#[test_action("neptune", "CreateEventSubscription", checksum = "035dd264")]
#[test_action("neptune", "CreateGlobalCluster", checksum = "8064be47")]
#[test_action("neptune", "DeleteDBCluster", checksum = "e4ac5e3b")]
#[test_action("neptune", "DeleteDBClusterEndpoint", checksum = "57e1fab7")]
#[test_action("neptune", "DeleteDBClusterParameterGroup", checksum = "7662ebcd")]
#[test_action("neptune", "DeleteDBClusterSnapshot", checksum = "3527ae42")]
#[test_action("neptune", "DeleteDBInstance", checksum = "00c780d6")]
#[test_action("neptune", "DeleteDBParameterGroup", checksum = "4a2dd299")]
#[test_action("neptune", "DeleteDBSubnetGroup", checksum = "5b4e4ea3")]
#[test_action("neptune", "DeleteEventSubscription", checksum = "94e5cad7")]
#[test_action("neptune", "DeleteGlobalCluster", checksum = "bd06908a")]
#[test_action("neptune", "DescribeDBClusterEndpoints", checksum = "67317958")]
#[test_action("neptune", "DescribeDBClusterParameterGroups", checksum = "fcc8e0c4")]
#[test_action("neptune", "DescribeDBClusterParameters", checksum = "b9b68238")]
#[test_action("neptune", "DescribeDBClusterSnapshotAttributes", checksum = "6c3b9874")]
#[test_action("neptune", "DescribeDBClusterSnapshots", checksum = "14da74a4")]
#[test_action("neptune", "DescribeDBClusters", checksum = "25bd768a")]
#[test_action("neptune", "DescribeDBEngineVersions", checksum = "3cfbeef3")]
#[test_action("neptune", "DescribeDBInstances", checksum = "8c1ee7ce")]
#[test_action("neptune", "DescribeDBParameterGroups", checksum = "ab1a6d87")]
#[test_action("neptune", "DescribeDBParameters", checksum = "80701b2d")]
#[test_action("neptune", "DescribeDBSubnetGroups", checksum = "22447678")]
#[test_action("neptune", "DescribeEngineDefaultClusterParameters", checksum = "2c17609c")]
#[test_action("neptune", "DescribeEngineDefaultParameters", checksum = "8ae25e5c")]
#[test_action("neptune", "DescribeEventCategories", checksum = "af7c16a1")]
#[test_action("neptune", "DescribeEventSubscriptions", checksum = "0d07d0ae")]
#[test_action("neptune", "DescribeEvents", checksum = "c9ffd127")]
#[test_action("neptune", "DescribeGlobalClusters", checksum = "b8b7f4fe")]
#[test_action("neptune", "DescribeOrderableDBInstanceOptions", checksum = "6d28934f")]
#[test_action("neptune", "DescribePendingMaintenanceActions", checksum = "51db8514")]
#[test_action("neptune", "DescribeValidDBInstanceModifications", checksum = "786c19f1")]
#[test_action("neptune", "FailoverDBCluster", checksum = "e7f21d77")]
#[test_action("neptune", "FailoverGlobalCluster", checksum = "8af95f1e")]
#[test_action("neptune", "ListTagsForResource", checksum = "e2fd0f82")]
#[test_action("neptune", "ModifyDBCluster", checksum = "81ca2a35")]
#[test_action("neptune", "ModifyDBClusterEndpoint", checksum = "b7f09ce1")]
#[test_action("neptune", "ModifyDBClusterParameterGroup", checksum = "fbbf555b")]
#[test_action("neptune", "ModifyDBClusterSnapshotAttribute", checksum = "efefb646")]
#[test_action("neptune", "ModifyDBInstance", checksum = "7cc8b0d7")]
#[test_action("neptune", "ModifyDBParameterGroup", checksum = "e380be71")]
#[test_action("neptune", "ModifyDBSubnetGroup", checksum = "55efe542")]
#[test_action("neptune", "ModifyEventSubscription", checksum = "7fef210d")]
#[test_action("neptune", "ModifyGlobalCluster", checksum = "65ada8ae")]
#[test_action("neptune", "PromoteReadReplicaDBCluster", checksum = "f75fc969")]
#[test_action("neptune", "RebootDBInstance", checksum = "83a085e9")]
#[test_action("neptune", "RemoveFromGlobalCluster", checksum = "588f154a")]
#[test_action("neptune", "RemoveRoleFromDBCluster", checksum = "5c76b75f")]
#[test_action("neptune", "RemoveSourceIdentifierFromSubscription", checksum = "8274566e")]
#[test_action("neptune", "RemoveTagsFromResource", checksum = "e2e69de2")]
#[test_action("neptune", "ResetDBClusterParameterGroup", checksum = "132743ba")]
#[test_action("neptune", "ResetDBParameterGroup", checksum = "99010cf8")]
#[test_action("neptune", "RestoreDBClusterFromSnapshot", checksum = "8cffcde5")]
#[test_action("neptune", "RestoreDBClusterToPointInTime", checksum = "38658e60")]
#[test_action("neptune", "StartDBCluster", checksum = "0e9248eb")]
#[test_action("neptune", "StopDBCluster", checksum = "b709afd2")]
#[test_action("neptune", "SwitchoverGlobalCluster", checksum = "509c5e90")]
#[tokio::test]
async fn neptune_probe() {
    let _server = TestServer::start().await;
}
