mod helpers;

use fakecloud_conformance_macros::test_action;
use helpers::TestServer;

#[test_action("opensearch", "AcceptInboundConnection", checksum = "314f91d1")]
#[test_action("opensearch", "AddDataSource", checksum = "e66a74f2")]
#[test_action("opensearch", "AddDirectQueryDataSource", checksum = "0789cf74")]
#[test_action("opensearch", "AddTags", checksum = "fb7378e7")]
#[test_action("opensearch", "AssociatePackage", checksum = "649aea25")]
#[test_action("opensearch", "AssociatePackages", checksum = "fd1c1317")]
#[test_action("opensearch", "AttachDataSource", checksum = "a8751d1d")]
#[test_action("opensearch", "AuthorizeVpcEndpointAccess", checksum = "a744f369")]
#[test_action("opensearch", "CancelDomainConfigChange", checksum = "06623235")]
#[test_action("opensearch", "CancelServiceSoftwareUpdate", checksum = "3ccb0e53")]
#[test_action("opensearch", "CreateApplication", checksum = "bcb878fc")]
#[test_action("opensearch", "CreateDomain", checksum = "5b691f10")]
#[test_action("opensearch", "CreateIndex", checksum = "076c3ed7")]
#[test_action("opensearch", "CreateOutboundConnection", checksum = "48aee630")]
#[test_action("opensearch", "CreatePackage", checksum = "9c52fff3")]
#[test_action("opensearch", "CreateVpcEndpoint", checksum = "86784dc8")]
#[test_action("opensearch", "DeleteApplication", checksum = "30eff383")]
#[test_action("opensearch", "DeleteDataSource", checksum = "aaa2b259")]
#[test_action("opensearch", "DeleteDirectQueryDataSource", checksum = "f774d316")]
#[test_action("opensearch", "DeleteDomain", checksum = "6b316f84")]
#[test_action("opensearch", "DeleteInboundConnection", checksum = "fc473b97")]
#[test_action("opensearch", "DeleteIndex", checksum = "2906539a")]
#[test_action("opensearch", "DeleteOutboundConnection", checksum = "4da07b91")]
#[test_action("opensearch", "DeletePackage", checksum = "9e538cec")]
#[test_action("opensearch", "DeleteVpcEndpoint", checksum = "5794e9fe")]
#[test_action("opensearch", "DeregisterCapability", checksum = "b209d1be")]
#[test_action("opensearch", "DescribeDataSourceAttachment", checksum = "7c9c0657")]
#[test_action("opensearch", "DescribeDomain", checksum = "5e7b8fb1")]
#[test_action("opensearch", "DescribeDomainAutoTunes", checksum = "36370bf4")]
#[test_action("opensearch", "DescribeDomainChangeProgress", checksum = "7e6be566")]
#[test_action("opensearch", "DescribeDomainConfig", checksum = "197399a5")]
#[test_action("opensearch", "DescribeDomainHealth", checksum = "a89f2a65")]
#[test_action("opensearch", "DescribeDomainNodes", checksum = "8e0aff7d")]
#[test_action("opensearch", "DescribeDomains", checksum = "57d7fb32")]
#[test_action("opensearch", "DescribeDryRunProgress", checksum = "f04ef25d")]
#[test_action("opensearch", "DescribeInboundConnections", checksum = "d78613c9")]
#[test_action("opensearch", "DescribeInsightDetails", checksum = "da26aead")]
#[test_action("opensearch", "DescribeInstanceTypeLimits", checksum = "d6451f26")]
#[test_action("opensearch", "DescribeOutboundConnections", checksum = "f2993d4d")]
#[test_action("opensearch", "DescribePackages", checksum = "102c6bac")]
#[test_action(
    "opensearch",
    "DescribeReservedInstanceOfferings",
    checksum = "1882bfad"
)]
#[test_action("opensearch", "DescribeReservedInstances", checksum = "d760f151")]
#[test_action("opensearch", "DescribeVpcEndpoints", checksum = "49401b30")]
#[test_action("opensearch", "DetachDataSource", checksum = "5e62a2c4")]
#[test_action("opensearch", "DissociatePackage", checksum = "cc0b5f4d")]
#[test_action("opensearch", "DissociatePackages", checksum = "ffb43ebe")]
#[test_action("opensearch", "GetApplication", checksum = "4b9353dd")]
#[test_action("opensearch", "GetCapability", checksum = "e8e6ae3f")]
#[test_action("opensearch", "GetCompatibleVersions", checksum = "db774b69")]
#[test_action("opensearch", "GetDataSource", checksum = "e1e19bdc")]
#[test_action("opensearch", "GetDefaultApplicationSetting", checksum = "a645c9cd")]
#[test_action("opensearch", "GetDirectQueryDataSource", checksum = "a74f691d")]
#[test_action("opensearch", "GetDomainMaintenanceStatus", checksum = "a6e15ec3")]
#[test_action("opensearch", "GetIndex", checksum = "edeb20c6")]
#[test_action("opensearch", "GetMigration", checksum = "efccfe6b")]
#[test_action("opensearch", "GetPackageVersionHistory", checksum = "d325be00")]
#[test_action("opensearch", "GetUpgradeHistory", checksum = "deabd562")]
#[test_action("opensearch", "GetUpgradeStatus", checksum = "adfcc62f")]
#[test_action("opensearch", "InsightFeedback", checksum = "3f5dd0e1")]
#[test_action("opensearch", "ListApplications", checksum = "6a9930dc")]
#[test_action("opensearch", "ListDataSourceAttachments", checksum = "86962871")]
#[test_action("opensearch", "ListDataSources", checksum = "ed8f3ee1")]
#[test_action("opensearch", "ListDirectQueryDataSources", checksum = "a65ce5fc")]
#[test_action("opensearch", "ListMigrations", checksum = "8c61e145")]
#[test_action("opensearch", "ListDomainMaintenances", checksum = "c423d0be")]
#[test_action("opensearch", "ListDomainNames", checksum = "e7f19430")]
#[test_action("opensearch", "ListDomainsForPackage", checksum = "07f9ec87")]
#[test_action("opensearch", "ListInsights", checksum = "515fc5b8")]
#[test_action("opensearch", "ListInstanceTypeDetails", checksum = "9b056b1f")]
#[test_action("opensearch", "ListPackagesForDomain", checksum = "5b6be208")]
#[test_action("opensearch", "ListScheduledActions", checksum = "103713df")]
#[test_action("opensearch", "ListTags", checksum = "65507cd0")]
#[test_action("opensearch", "ListVersions", checksum = "c1acf747")]
#[test_action("opensearch", "ListVpcEndpointAccess", checksum = "0cc173a6")]
#[test_action("opensearch", "ListVpcEndpoints", checksum = "e652300c")]
#[test_action("opensearch", "ListVpcEndpointsForDomain", checksum = "5a67ccf6")]
#[test_action(
    "opensearch",
    "PurchaseReservedInstanceOffering",
    checksum = "512c7cc6"
)]
#[test_action("opensearch", "PutDefaultApplicationSetting", checksum = "1a35b2c9")]
#[test_action("opensearch", "RegisterCapability", checksum = "6ce86326")]
#[test_action("opensearch", "RejectInboundConnection", checksum = "e6e7a0ff")]
#[test_action("opensearch", "RemoveTags", checksum = "068b7737")]
#[test_action("opensearch", "RevokeVpcEndpointAccess", checksum = "68397194")]
#[test_action("opensearch", "RollbackServiceSoftwareUpdate", checksum = "842bb354")]
#[test_action("opensearch", "StartDomainMaintenance", checksum = "2ca30331")]
#[test_action("opensearch", "StartMigration", checksum = "bd4167ae")]
#[test_action("opensearch", "StartServiceSoftwareUpdate", checksum = "7ee207b2")]
#[test_action("opensearch", "UpdateApplication", checksum = "6bfb0021")]
#[test_action("opensearch", "UpdateDataSource", checksum = "17dd9f7d")]
#[test_action("opensearch", "UpdateDirectQueryDataSource", checksum = "a022bd6f")]
#[test_action("opensearch", "UpdateDomainConfig", checksum = "7919b267")]
#[test_action("opensearch", "UpdateIndex", checksum = "8888ec3a")]
#[test_action("opensearch", "UpdatePackage", checksum = "776d68d3")]
#[test_action("opensearch", "UpdatePackageScope", checksum = "bdcd7a52")]
#[test_action("opensearch", "UpdateScheduledAction", checksum = "778a4034")]
#[test_action("opensearch", "UpdateVpcEndpoint", checksum = "9e11efb2")]
#[test_action("opensearch", "UpgradeDomain", checksum = "eb797188")]
#[tokio::test]
async fn opensearch_probe() {
    let _server = TestServer::start().await;
}
