//! Transfer Family (`transfer`) awsJson1.1 conformance probe assertions.
//!
//! One `#[test_action]` per operation in the Transfer Family Smithy model.
//! Checksums are harvested from `aws-models/transfer.json`; the probe
//! generates request variants per operation and asserts fakecloud responds
//! AWS-faithfully.

mod helpers;

use fakecloud_conformance_macros::test_action;
use helpers::TestServer;

#[test_action("transfer", "CreateAccess", checksum = "482198aa")]
#[test_action("transfer", "CreateAgreement", checksum = "5ff5b981")]
#[test_action("transfer", "CreateConnector", checksum = "578da32e")]
#[test_action("transfer", "CreateProfile", checksum = "0e1e3546")]
#[test_action("transfer", "CreateServer", checksum = "ea5dbf8a")]
#[test_action("transfer", "CreateUser", checksum = "d6286e25")]
#[test_action("transfer", "CreateWebApp", checksum = "bd0dd462")]
#[test_action("transfer", "CreateWorkflow", checksum = "696a3a07")]
#[test_action("transfer", "DeleteAccess", checksum = "548e462d")]
#[test_action("transfer", "DeleteAgreement", checksum = "9506efcb")]
#[test_action("transfer", "DeleteCertificate", checksum = "97b2d9b4")]
#[test_action("transfer", "DeleteConnector", checksum = "1db58cf4")]
#[test_action("transfer", "DeleteHostKey", checksum = "62f809a1")]
#[test_action("transfer", "DeleteProfile", checksum = "b5eb80ae")]
#[test_action("transfer", "DeleteServer", checksum = "6f305e55")]
#[test_action("transfer", "DeleteSshPublicKey", checksum = "f6b49744")]
#[test_action("transfer", "DeleteUser", checksum = "19757e28")]
#[test_action("transfer", "DeleteWebApp", checksum = "eeb211c4")]
#[test_action("transfer", "DeleteWebAppCustomization", checksum = "e8cbbd5a")]
#[test_action("transfer", "DeleteWorkflow", checksum = "8daf485f")]
#[test_action("transfer", "DescribeAccess", checksum = "610847ce")]
#[test_action("transfer", "DescribeAgreement", checksum = "21085849")]
#[test_action("transfer", "DescribeCertificate", checksum = "2754344d")]
#[test_action("transfer", "DescribeConnector", checksum = "bbeaac81")]
#[test_action("transfer", "DescribeExecution", checksum = "348aaf31")]
#[test_action("transfer", "DescribeHostKey", checksum = "8c8a69e5")]
#[test_action("transfer", "DescribeProfile", checksum = "d9d8da1a")]
#[test_action("transfer", "DescribeSecurityPolicy", checksum = "fda492fe")]
#[test_action("transfer", "DescribeServer", checksum = "6ba52588")]
#[test_action("transfer", "DescribeUser", checksum = "e8862054")]
#[test_action("transfer", "DescribeWebApp", checksum = "22d46bc7")]
#[test_action("transfer", "DescribeWebAppCustomization", checksum = "d25880c8")]
#[test_action("transfer", "DescribeWorkflow", checksum = "2fd4f5c6")]
#[test_action("transfer", "ImportCertificate", checksum = "1cedd4c5")]
#[test_action("transfer", "ImportHostKey", checksum = "74741f88")]
#[test_action("transfer", "ImportSshPublicKey", checksum = "4d50d80c")]
#[test_action("transfer", "ListAccesses", checksum = "9d9895ff")]
#[test_action("transfer", "ListAgreements", checksum = "828fe443")]
#[test_action("transfer", "ListCertificates", checksum = "28065eeb")]
#[test_action("transfer", "ListConnectors", checksum = "75c5d970")]
#[test_action("transfer", "ListExecutions", checksum = "10c919da")]
#[test_action("transfer", "ListFileTransferResults", checksum = "b8fd7d0e")]
#[test_action("transfer", "ListHostKeys", checksum = "e7bc64fc")]
#[test_action("transfer", "ListProfiles", checksum = "3239a92b")]
#[test_action("transfer", "ListSecurityPolicies", checksum = "a4567012")]
#[test_action("transfer", "ListServers", checksum = "6b857724")]
#[test_action("transfer", "ListTagsForResource", checksum = "a71e5b6d")]
#[test_action("transfer", "ListUsers", checksum = "69cc1e51")]
#[test_action("transfer", "ListWebApps", checksum = "9376298b")]
#[test_action("transfer", "ListWorkflows", checksum = "ddb40c6c")]
#[test_action("transfer", "SendWorkflowStepState", checksum = "aee0c8f7")]
#[test_action("transfer", "StartDirectoryListing", checksum = "efcd468d")]
#[test_action("transfer", "StartFileTransfer", checksum = "087dc798")]
#[test_action("transfer", "StartRemoteDelete", checksum = "ff76bd60")]
#[test_action("transfer", "StartRemoteMove", checksum = "935cb709")]
#[test_action("transfer", "StartServer", checksum = "7a0591da")]
#[test_action("transfer", "StopServer", checksum = "0a7099d2")]
#[test_action("transfer", "TagResource", checksum = "d7eb0fd8")]
#[test_action("transfer", "TestConnection", checksum = "a30e44f2")]
#[test_action("transfer", "TestIdentityProvider", checksum = "10f0daa5")]
#[test_action("transfer", "UntagResource", checksum = "e1327a6a")]
#[test_action("transfer", "UpdateAccess", checksum = "018643a1")]
#[test_action("transfer", "UpdateAgreement", checksum = "bde6c56f")]
#[test_action("transfer", "UpdateCertificate", checksum = "07521e17")]
#[test_action("transfer", "UpdateConnector", checksum = "a7ff2a02")]
#[test_action("transfer", "UpdateHostKey", checksum = "d6bce871")]
#[test_action("transfer", "UpdateProfile", checksum = "b2283ba5")]
#[test_action("transfer", "UpdateServer", checksum = "56339d3e")]
#[test_action("transfer", "UpdateUser", checksum = "fea09f51")]
#[test_action("transfer", "UpdateWebApp", checksum = "becaeaed")]
#[test_action("transfer", "UpdateWebAppCustomization", checksum = "94d03877")]
#[tokio::test]
async fn transfer_probe() {
    let _server = TestServer::start().await;
}
